#!/usr/bin/env bun

import { Command } from "commander";
import { sort } from "radash";
import invariant from "tiny-invariant";
import { getTimestamp, getTimestampFromFarcasterTimestamp } from "./src/hubs";
import {
	deleteCast,
	follow,
	getCasts,
	getFidFromUsername,
	getLikesByFid,
	getReactionsByCast,
	unfollow,
} from "./src/hypersnap";
import {
	getFollowers,
	getFollowing,
	getUserInfo,
	lookupCastByHashOrWarpcastUrl,
} from "./src/neynar";
import { getBalance, getUSDCBalance } from "./src/rpc";
import { urlToCastHash } from "./src/shim";
import { firstNUnique, readAllStdin, shortenAddress } from "./src/utils";
import { wrappa } from "./src/wrappa";

const program = new Command();

program.name("hyper").description("Hypersnap CLI").version("0.1.0");

program
	.command("ls")
	.description("List most recent casts+replies")
	.argument("<user>", "user to list casts for")
	.action(async (user) => {
		const fid = await getFidFromUsername(user);
		invariant(fid, `User not found: ${user}`);

		const casts = await getCasts(fid, true, 10);
		console.log(
			casts
				.map(
					(c) =>
						`${getTimestamp(getTimestampFromFarcasterTimestamp(c.timestamp ?? 0))} ${c.text.slice(0, 70)} [${c.hash.slice(0, 10)}]`,
				)
				.join("\n"),
		);
	});

program
	.command("url")
	.description("Resolve a cast URL to a full hash")
	.argument("<url>", "URL to resolve")
	.action(async (url) => {
		const hash = await urlToCastHash(url);
		console.log(hash);
	});

program
	.command("like")
	.description("Like a cast")
	.argument("<url>", "URL to like")
	.action(async (url) => {
		const hash = await urlToCastHash(url);
		invariant(hash, `Cast not found: ${url}`);
		await wrappa({ action: "like", hashOrUrl: hash });
	});

program
	.command("cast")
	.description("Cast a message")
	.argument("[message]", "Message to cast")
	.option("-c, --channel <channel>", "Channel to cast to")
	.option(
		"-e, --embed <url>",
		"URL to embed",
		(value: string, previous: string[]) => previous.concat([value]),
		[] as string[],
	)
	.action(async (message, options) => {
		const maybeFatText = message !== undefined ? message : await readAllStdin();
		const text = maybeFatText.trimEnd();
		invariant(text.length > 0, "Text not provided or is empty");

		invariant(
			options.embed.length <= 2,
			`Too many embeds: got ${options.embed.length}, max is 2`,
		);
		invariant(
			options.embed.every((u) => u.trim().length > 0),
			"Embed URLs cannot be empty",
		);

		await wrappa({
			action: "cast",
			text,
			channelId: options.channel,
			attachments: options.embed,
		});
	});

program
	.command("boost")
	.description("Boost a cast by liking + recasting")
	.argument("<url>", "URL to boost")
	.action(async (url) => {
		await wrappa({ action: "like+recast", hashOrUrl: url });
	});

program
	.command("reply")
	.description("Reply to a cast")
	.argument("<url>", "URL to reply to")
	.argument("<message>", "Message to reply with")
	.option("-l, --like", "also like the cast")
	.action(async (url, message, options) => {
		const action = options.like ? "like+reply" : "reply";
		await wrappa({ action, hashOrUrl: url, text: message });
	});

program
	.command("delete")
	.description("Delete a cast")
	.argument("<url>", "URL to delete")
	.action(async (url) => {
		const hash = await urlToCastHash(url);
		invariant(hash, `Cast not found: ${url}`);
		await deleteCast(`0x${hash.replace("0x", "")}`);
	});

program
	.command("who-liked")
	.description("Who liked a cast")
	.argument("<url>", "URL to get who liked")
	.action(async (url) => {
		const cast = await lookupCastByHashOrWarpcastUrl(url);
		invariant(cast, `Cast not found: ${url}`);
		const reactoooors = await getReactionsByCast(
			cast.cast.author.fid,
			`0x${cast.cast.hash.replace("0x", "")}`,
		);
		(reactoooors ?? []).forEach(async (fid) => {
			if (!fid) return;
			const user = await getUserInfo(fid);
			console.log(`${user?.username} [${fid}]`);
		});
	});

program
	.command("frens")
	.description("List frens by most recent likes")
	.option("-n, --limit <limit>", "Limit the number of frens to list", "5")
	.action(async (options) => {
		const limit = Number(options.limit ?? 5);
		const frens = await getLikesByFid(Number(process.env.FID));
		await Promise.all(
			firstNUnique(
				sort(frens ?? [], (f) => f.timestamp ?? 0, true),
				(f) => f.targetFid,
				limit,
			)
				.map((f) => f.targetFid)
				.slice(0, limit)
				.map(async (f) => {
					if (!f) return;
					const user = await getUserInfo(f);
					console.log(`${user?.username}`);
				}),
		);
	});

program
	.command("user")
	.description("Get user info")
	.argument("<username>", "Username to get info for")
	.action(async (username) => {
		// const user = await getUserByUsername(username);
		const fid = await getFidFromUsername(username);
		invariant(fid, `User not found: ${username}`);
		const user = await getUserInfo(fid);
		console.log(user);
	});

program
	.command("user-info")
	.description("Get user info")
	.argument("<fid>", "FID to get info for")
	.action(async (fid) => {
		const user = await getUserInfo(Number(fid));
		console.log(user);
	});

program
	.command("balance")
	.description("Get balance")
	.argument("<username>", "Username to get balance for")
	.action(async (username) => {
		const fid = await getFidFromUsername(username);
		invariant(fid, `User not found: ${username}`);
		const user = await getUserInfo(fid);
		invariant(user, `User not found: ${username}`);
		const primaryAddress = user.verified_addresses.primary.eth_address;
		invariant(primaryAddress, `Primary address not found: ${username}`);
		console.log(
			`[${fid}] ${user.username} ${shortenAddress(primaryAddress)} (primary)`,
		);
		const ethBalance = await getBalance(primaryAddress);
		const usdcBalance = await getUSDCBalance(primaryAddress);
		console.log(
			`Base: ${ethBalance.toFixed(4)} ETH, ${usdcBalance.toFixed(2)} USDC`,
		);
	});

program
	.command("follow")
	.description("Follow a user")
	.argument("<fid>", "FID to follow")
	.action(async (fid) => {
		await follow(Number(fid));
	});

program
	.command("unfollow")
	.description("Unfollow a user")
	.argument("<fid>", "FID to unfollow")
	.action(async (fid) => {
		await unfollow(Number(fid));
	});

program
	.command("following")
	.description("List following")
	.option("-f, --fid <fid>", "FID to list following for", process.env.FID)
	.action(async (options) => {
		const fid = Number(options.fid ?? process.env.FID);
		const following = await getFollowing(fid);
		// console.log(following);
		console.log(
			(following?.users ?? [])
				.map((f) => `${f.username} [${f.fid}]`)
				.join("\n"),
		);
	});

program
	.command("followers")
	.description("List followers")
	.option("-f, --fid <fid>", "FID to list followers for", process.env.FID)
	.action(async (options) => {
		const fid = Number(options.fid ?? process.env.FID);
		const followers = await getFollowers(fid);
		console.log(
			(followers?.users ?? [])
				.map((f) => `${f.username} [${f.fid}]`)
				.join("\n"),
		);
	});

program
	.command("whoami")
	.description("Get whoami")
	.action(async () => {
		const user = await getUserInfo(Number(process.env.FID));
		console.log(user);
	});

program.parse();
